from handlers.signup import Register
from handlers.login import Login
from handlers.logout import Logout
from handlers.newpost import NewPost
from handlers.newcomment import NewComment
from handlers.editcomment import EditComment
from handlers.deletecomment import DeleteComment
from handlers.likepost import LikePost
from handlers.editpost import EditPost
from handlers.deletepost import DeletePost
from handlers.permalink import PostPage
from handlers.blog import *
from utils import *
from decorators import *
